"""The SEAL certificate-of-erasure protocol.

Two channels, run by the party that wants assurance (the data owner /
regulator), never by the model owner:

  Channel A (zero marginal privacy cost). The client re-evaluates its OWN
  forgotten records D_i under the pre-request model M and the post-request
  model M'. Because D_i is data the client already possesses in full, this
  channel leaks nothing about anyone else's membership. It catches a
  server that simply did nothing ("lazy" dishonesty), but a server can spoof
  it by fine-tuning on exactly D_i (see seal.mechanisms.dishonest_spoof).

  Channel B (tunable, bounded privacy cost). The client also queries M' at
  a budget of B synthetic probes generated by small perturbations of its
  own forgotten records (never touching another party's raw data). The
  server's responses are released through a Gaussian mechanism calibrated
  to a target (epsilon, delta) retained-set privacy budget (seal.privacy).
  A server that only spoofed the exact forgotten points -- and left the
  surrounding decision boundary untouched -- is exposed here, because
  honest unlearning moves the loss on nearby points too (via the training
  objective's influence function) while spoofing does not.

Both channels are compared against a calibrated null distribution built
from a public reference/calibration corpus that is disjoint from any
client's private data, giving thresholds with a controlled Type-I error
(false accusation) rate.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy import stats

from .flmodel import FederatedSoftmax, Params
from .privacy import PrivacyBudget, calibrate_sigma


def _predictive_quantile(beta: float, n_calib: int) -> float:
    """The exact finite-sample threshold multiplier for testing a fresh
    observation against a null estimated from `n_calib` i.i.d. calibration
    replicates, instead of the asymptotic z-quantile `stats.norm.ppf(1-beta)`
    that assumes the calibration mean/std are the true population values.

    If the n_calib replicates and the real audited statistic are i.i.d.
    N(mu, sigma^2) under the null, then by Cochran's theorem the sample
    mean and sample variance of the replicates are independent, so

        (T_new - mean(replicates)) / (std(replicates) * sqrt(1 + 1/n_calib))

    is exactly Student-t distributed with (n_calib - 1) degrees of freedom
    -- not standard normal -- because it is the ratio of a normal variate
    to an independent (scaled) chi-distributed one (this is the classical
    "prediction interval for a future observation" result, not something
    original to this project). Substituting the t-quantile here, scaled by
    sqrt(1 + 1/n_calib), gives EXACT Type-I error control at the stated
    beta under that Gaussian idealization; the z-quantile plug-in this
    project used previously does not, and understates the true threshold
    distance most severely at the small calibration-replicate counts this
    project's own experiments actually ran with (e.g. n_calib=2 in the LLM
    track: t_crit(1 df) = 6.31 vs z_crit = 1.64, a 3.8x difference) --
    which is the exact, provable explanation for the excess false-
    accusation rate documented in docs/RESULTS.md and docs/RESULTS_LLM.md.
    """
    if n_calib < 2:
        raise ValueError("need >=2 calibration replicates for a defined sample std")
    t_crit = stats.t.ppf(1 - beta, df=n_calib - 1)
    return t_crit * np.sqrt(1 + 1 / n_calib)


@dataclass
class ChannelStats:
    lam: float
    threshold: float
    z: float
    flagged: bool


@dataclass
class SealResult:
    channel_a: ChannelStats
    channel_b: ChannelStats
    decision_dishonest: bool
    budget: PrivacyBudget
    beta_target: float


def _loss_gap(model: FederatedSoftmax, X: np.ndarray, y: np.ndarray, before: Params, after: Params) -> float:
    if len(X) == 0:
        return 0.0
    return float(np.mean(model.per_sample_loss(X, y, after) - model.per_sample_loss(X, y, before)))


def make_probes(X: np.ndarray, y: np.ndarray, n_probes: int, jitter: float, seed: int):
    """Synthetic near-neighbor probes generated ONLY from the client's own
    forgotten records (label-preserving small perturbation assumption)."""
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(X), size=n_probes)
    noise = rng.normal(scale=jitter, size=(n_probes, X.shape[1]))
    return X[idx] + noise, y[idx]


def _noisy_loss_gap(
    model: FederatedSoftmax,
    Xp: np.ndarray,
    yp: np.ndarray,
    before: Params,
    after: Params,
    sigma: float,
    l_max: float,
    seed: int,
) -> float:
    if len(Xp) == 0:
        return 0.0
    loss_before = np.clip(model.per_sample_loss(Xp, yp, before), 0, l_max)
    loss_after = np.clip(model.per_sample_loss(Xp, yp, after), 0, l_max)
    rng = np.random.default_rng(seed)
    if np.isfinite(sigma):
        loss_after_noisy = loss_after + rng.normal(scale=sigma, size=loss_after.shape)
    else:
        loss_after_noisy = loss_after
    return float(np.mean(loss_after_noisy - loss_before))


@dataclass
class CalibReplicate:
    Xf: np.ndarray
    yf: np.ndarray
    before_ref: Params
    after_ref: Params


def build_calibration_replicates(calib_X, calib_y, before: Params, unlearn_fn, n_reps: int, seed: int, m: int) -> list[CalibReplicate]:
    """Build the honest-unlearning reference replicates from a public
    calibration corpus disjoint from any client's private data. This is the
    expensive step (it reruns the honest mechanism `n_reps` times) but does
    not depend on the audit's epsilon budget, so callers should build it
    once per (dataset, forget-request) and reuse it across an epsilon sweep.

    `unlearn_fn(Xf, yf, before, seed)` must return `(before_ref, after_ref)`:
    a state that genuinely included `(Xf, yf)` during training from the
    start (mirroring how the real forgotten records were baked into the
    original model), and the state obtained by honestly removing it and
    continuing to train. Comparing against a fixed pre-request `before`
    that never actually incorporated the calibration subset -- or only
    warm-started it late -- does not mirror the real request and gives a
    degenerate, near-zero null.
    """
    rng = np.random.default_rng(seed)
    n = len(calib_X)
    reps = []
    for r in range(n_reps):
        sub = rng.choice(n, size=min(m, n), replace=False)
        Xf, yf = calib_X[sub], calib_y[sub]
        before_ref, after_ref = unlearn_fn(Xf, yf, before, seed * 7919 + r)
        reps.append(CalibReplicate(Xf, yf, before_ref, after_ref))
    return reps


class SealCertificate:
    """Runs the two-channel audit and issues an accept/reject certificate."""

    def __init__(
        self,
        model: FederatedSoftmax,
        l_max: float = 8.0,
        n_probes: int = 50,
        jitter: float = 0.5,
        epsilon_audit: float = 1.0,
        delta_audit: float = 1e-5,
        beta_target: float = 0.05,
    ):
        self.model = model
        self.l_max = l_max
        self.n_probes = n_probes
        self.jitter = jitter
        self.epsilon_audit = epsilon_audit
        self.delta_audit = delta_audit
        self.beta_target = beta_target
        self.budget = calibrate_sigma(epsilon_audit, delta_audit, n_probes, sensitivity=l_max)

    def _null_from_replicates(self, reps: list[CalibReplicate], seed: int):
        a_vals, b_vals = [], []
        for i, rep in enumerate(reps):
            a_vals.append(_loss_gap(self.model, rep.Xf, rep.yf, rep.before_ref, rep.after_ref))
            Xp, yp = make_probes(rep.Xf, rep.yf, self.n_probes, self.jitter, seed=seed * 104729 + i)
            b_vals.append(
                _noisy_loss_gap(self.model, Xp, yp, rep.before_ref, rep.after_ref, self.budget.sigma, self.l_max, seed=seed * 15485863 + i)
            )
        return np.array(a_vals), np.array(b_vals)

    def audit(
        self,
        forget_X: np.ndarray,
        forget_y: np.ndarray,
        before: Params,
        after: Params,
        calib_replicates: list[CalibReplicate],
        seed: int = 0,
    ) -> SealResult:
        beta_per_channel = self.beta_target / 2.0  # Bonferroni split across the two channels

        null_a, null_b = self._null_from_replicates(calib_replicates, seed)
        mu_a, sd_a = float(null_a.mean()), float(null_a.std(ddof=1) + 1e-9)
        mu_b, sd_b = float(null_b.mean()), float(null_b.std(ddof=1) + 1e-9)

        tau_a = mu_a - _predictive_quantile(beta_per_channel, len(null_a)) * sd_a
        tau_b = mu_b - _predictive_quantile(beta_per_channel, len(null_b)) * sd_b

        lam_a = _loss_gap(self.model, forget_X, forget_y, before, after)
        Xp, yp = make_probes(forget_X, forget_y, self.n_probes, self.jitter, seed=seed + 1)
        lam_b = _noisy_loss_gap(self.model, Xp, yp, before, after, self.budget.sigma, self.l_max, seed=seed + 2)

        za = (lam_a - mu_a) / sd_a
        zb = (lam_b - mu_b) / sd_b
        ca = ChannelStats(lam=lam_a, threshold=tau_a, z=za, flagged=lam_a < tau_a)
        cb = ChannelStats(lam=lam_b, threshold=tau_b, z=zb, flagged=lam_b < tau_b)

        return SealResult(
            channel_a=ca,
            channel_b=cb,
            decision_dishonest=ca.flagged or cb.flagged,
            budget=self.budget,
            beta_target=self.beta_target,
        )
